Added fix for simplecov crashing with following error:
/home/golly/.rvm/gems/ruby-1.9.3-p194/gems/simplecov-0.6.4/lib/simplecov/result_merger.rb:77:in
`block in store_result': undefined method `pretty_generate' for
JSON:Module (NoMethodError)
	from
/home/golly/.rvm/gems/ruby-1.9.3-p194/gems/simplecov-0.6.4/lib/simplecov/result_merger.rb:75:in
`open'
	from
/home/golly/.rvm/gems/ruby-1.9.3-p194/gems/simplecov-0.6.4/lib/simplecov/result_merger.rb:75:in
`store_result'
	from
/home/golly/.rvm/gems/ruby-1.9.3-p194/gems/simplecov-0.6.4/lib/simplecov.rb:48:in
`result'
	from /home/golly/projects/corvid/lib/corvid/test/simplecov.rb:2:in
`add_files_to_coverage'
	from /home/golly/projects/corvid/lib/corvid/test/simplecov.rb:21:in
`block in add_files_to_coverage_at_exit'
	from
/home/golly/.rvm/gems/ruby-1.9.3-p194/gems/simplecov-0.6.4/lib/simplecov/defaults.rb:51:in
`call'
	from
/home/golly/.rvm/gems/ruby-1.9.3-p194/gems/simplecov-0.6.4/lib/simplecov/defaults.rb:51:in
`block in <top (required)>'